ERROR_MESSAGE = 'TYPE MISMATCH'

# TODO VOID HANDLING IF NEEDED Y CONECTARLE LOGICA

SemanticCube = {
  '+': {
    'int': {
      'int': 'int',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'flt',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '-': {
    'int': {
      'int': 'int',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'flt',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '*': {
    'int': {
      'int': 'int',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'flt',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '/': {
    'int': {
      'int': 'flt',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'flt',
      'flt': 'flt',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },  
  '>': {
    'int': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '<': {
    'int': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '>=': {
    'int': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '<=': {
    'int': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': 'boo',
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
  },
  '==': {
    'int': {
      'int': 'boo',
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': ERROR_MESSAGE,
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': 'boo',
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': 'boo', 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': 'boo',
    }, 
  },
  '!=': {
    'int': {
      'int': 'boo',
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': ERROR_MESSAGE,
      'flt': 'boo',
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': 'boo',
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': 'boo', 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': 'boo',
    }, 
  },
  '&&': {
    'int': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': 'boo',
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
  },
  '||': {
    'int': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    }, 
    'flt': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'boo': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': 'boo',
      'str': ERROR_MESSAGE,
    },
    'cha': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
    'str': {
      'int': ERROR_MESSAGE,
      'flt': ERROR_MESSAGE,
      'cha': ERROR_MESSAGE, 
      'boo': ERROR_MESSAGE,
      'str': ERROR_MESSAGE,
    },
  },
}

def returningType(left, right, op):
  return SemanticCube[op][left][right]