ERROR_MESSAGE = 'TYPE MISMATCH'

# TODO VOID HANDLING IF NEEDED Y CONECTARLE LOGICA

semanticCube = {
  '+': {
    'int': {
      'int': 'int',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'float',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '-': {
    'int': {
      'int': 'int',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'float',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '*': {
    'int': {
      'int': 'int',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'float',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '/': {
    'int': {
      'int': 'float',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'float',
      'float': 'float',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },  
  '>': {
    'int': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '<': {
    'int': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '>=': {
    'int': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '<=': {
    'int': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': 'bool',
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
  },
  '==': {
    'int': {
      'int': 'bool',
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': ERROR_MESSAGE,
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': 'bool',
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': 'bool', 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': 'bool',
    }, 
  },
  '!=': {
    'int': {
      'int': 'bool',
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': ERROR_MESSAGE,
      'float': 'bool',
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': 'bool',
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': 'bool', 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': 'bool',
    }, 
  },
  '&&': {
    'int': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': 'bool',
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
  },
  '||': {
    'int': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    }, 
    'float': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'bool': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': 'bool',
      'string': ERROR_MESSAGE,
    },
    'char': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
    'string': {
      'int': ERROR_MESSAGE,
      'float': ERROR_MESSAGE,
      'char': ERROR_MESSAGE, 
      'bool': ERROR_MESSAGE,
      'string': ERROR_MESSAGE,
    },
  },
}